name: Github Action
on: [push]
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 # clone ur repo
            - uses: actions/setup-node@v3
              with:
                node-version: 14
            - run: node -v